#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
SKETCH="$ROOT/firmware/emg_ota"
BUILD="$ROOT/build"
FQBN="esp32:esp32:esp32"
ESPOTA="$HOME/.arduino15/packages/esp32/hardware/esp32/2.0.10/tools/espota.py"
OTA_HOST="${OTA_HOST:-emg-esp32.local}"
OTA_PORT=3232

# ── load .env (safe parse — handles spaces, !, special chars) ────────────────
if [[ ! -f "$ROOT/.env" ]]; then
  echo "ERROR: .env not found — copy .env.example to .env and fill in credentials"
  exit 1
fi
while IFS='=' read -r key value; do
  [[ -z "$key" || "$key" == \#* ]] && continue
  printf -v "$key" '%s' "$value"
  export "$key"
done < "$ROOT/.env"

: "${WIFI_SSID:?WIFI_SSID not set in .env}"
: "${WIFI_PASSWORD:?WIFI_PASSWORD not set in .env}"
: "${OTA_PASSWORD:?OTA_PASSWORD not set in .env}"

# ── generate secrets.h (avoids all quoting issues with special chars/spaces) ──
SECRETS="$SKETCH/secrets.h"
cat > "$SECRETS" <<EOF
// auto-generated by flash.sh — do not edit, do not commit
#pragma once
#define WIFI_SSID     "${WIFI_SSID}"
#define WIFI_PASSWORD "${WIFI_PASSWORD}"
#define OTA_PASSWORD  "${OTA_PASSWORD}"
EOF
echo "==> secrets.h written"

# ── compile ───────────────────────────────────────────────────────────────────
echo "==> Compiling..."
arduino-cli compile \
  --fqbn "$FQBN" \
  --build-path "$BUILD" \
  "$SKETCH"

BIN="$BUILD/emg_ota.ino.bin"

# ── upload: OTA preferred, USB fallback ──────────────────────────────────────
if ping -c1 -W1 "$OTA_HOST" &>/dev/null 2>&1; then
  echo "==> OTA flash → $OTA_HOST"
  python3 "$ESPOTA" \
    -i "$OTA_HOST" \
    -p "$OTA_PORT" \
    -a "$OTA_PASSWORD" \
    -f "$BIN"
else
  # detect first available USB serial port
  PORT=$(find /dev -maxdepth 1 \( -name 'ttyUSB*' -o -name 'ttyACM*' \) 2>/dev/null | sort | head -1)
  if [[ -z "$PORT" ]]; then
    echo "ERROR: ESP32 not reachable via OTA ($OTA_HOST) and no USB port found"
    exit 1
  fi
  echo "==> USB flash → $PORT  (OTA not reachable)"
  arduino-cli upload \
    --fqbn "$FQBN" \
    --port "$PORT" \
    --input-dir "$BUILD"
fi

echo "==> Done."
